import {
  BRANCH,
  GITHUB_RAW_BASE_URL,
  POKEMON_API_BASE,
  POKEMON_API_RESOURCE,
  POKEMON_API_VERSION,
  REPO_NAME,
  REPO_OWNER,
  SPRITES_PATH,
} from '../env';

export const endpoint = {
  POKEMON: `${POKEMON_API_BASE}/${POKEMON_API_VERSION}/${POKEMON_API_RESOURCE}`,
  URL_IMG_POKEMON: `${GITHUB_RAW_BASE_URL}/${REPO_OWNER}/${REPO_NAME}/${BRANCH}/${REPO_NAME}/${POKEMON_API_RESOURCE}/${SPRITES_PATH}`,
};
